### ISSUE TITLE
onContentSizeChange prop is not being ran

### ISSUE THREAD

**Issue by chenop** [mak12/rn-faded-scrollview#3]
When passing onContentSizeChange callback it is not being ran.
It happens because this package has its own implementation for that

change needed:
```
onContentSizeChange = (contentWidth, contentHeight) => {
        // Save the content height in state
        this.setState({ scrollHeight: contentHeight, scrollWidth: contentWidth });
        this.props.onContentSizeChange(contentWidth, contentHeight); // <-- Add this
    };
```

**Comment by mak12** [comment]
Sorry for the delays, issue is fixed in latest release [1.0.11](https://www.npmjs.com/package/rn-faded-scrollview)
