### ISSUE TITLE
onScroll is not being passed with the event param

### ISSUE THREAD

**Issue by chenop** [mak12/rn-faded-scrollview#6]
in onScrolled function - there is the following code:
`
       if (this.props.onScroll) {
              this.props.onScroll();
        }
`

should be:
`
       if (this.props.onScroll) {
               this.props.onScroll(e);
        }
`

**Comment by mak12** [comment]
@chenop Thank you for reporting it, let me check

**Comment by chenop** [comment]
Thanks for revieweing - fixed 
For some reason it display an invisible diff in Readme.Md (although nothing was changed)

**Comment by chenop** [comment]
@mak12 - is it ok it merge this?

**Comment by mak12** [comment]
merged!!
fixed in release 1.0.12
