### ISSUE TITLE
Make ScrollView Keyboard-Aware

### ISSUE THREAD

**Issue by agustinfece** [mak12/rn-faded-scrollview#9]
I need to add fade to my current implementation that uses `KeyboardAwareScrollView` so it doesn't overlap text inputs

**Comment by mak12** [comment]
Hi @agustinfece 
`KeyboardAwareScrollView` is a separate component which uses `react-native's` `scrollview`.
After looking into their docs , they have `HOC` component that can be used with our `faded-scrollview`
Please have a look into [this](https://github.com/APSL/react-native-keyboard-aware-scroll-view#using-high-order-component).
If you have any more questions, feel free to ask.
